Fix dropdown menu on mobile devices
DataWorkz-NL/dataworkz-site pull request #34
Opened 2021-03-16 15:34 UTC by fabiopaiva

2021-03-19 08:43 UTC, jkokkeler requested changes
Check to see if you can fix those

2021-03-19 08:58 UTC, fabiopaiva commented on layouts/partials/header.html
> +              <a class="nav-link dropdown-toggle" {{ if .URL }} href="{{ .URL | relLangURL }}" {{ end }}>
It has to be clickable. On mobile devices, the tap will trigger the dropdown, not the `hover` event. 
This is how Bootstrap works. https://getbootstrap.com/docs/4.0/components/navs/#tabs-with-dropdowns
To improve it I could add some accessibility parameters
```
<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
```

2021-03-19 08:59 UTC, fabiopaiva commented on config.toml
> -URL = "solutions"
what do you mean by `top`?

2021-03-19 09:14 UTC, fabiopaiva commented on config.toml
> -URL = "solutions"
ah, I think I understood it. You mean, a link to the top of the page. 
I think we could add a new dropdown menu item called `Our solutions`?

2021-03-19 09:41 UTC, fabiopaiva commented on assets/scss/templates/_navigation.scss
> +        display: block;
I couldn't reproduce it. It worked fine on my phone. 
Or did I misunderstand the problem?

https://user-images.githubusercontent.com/2126528/111760677-4690bb80-889f-11eb-803e-e6dfe4698c51.MOV

2021-03-22 15:21 UTC, jkokkeler commented on config.toml
> -URL = "solutions"
Could be, check with Martin

2021-03-22 15:21 UTC, jkokkeler commented on layouts/partials/header.html
> +              <a class="nav-link dropdown-toggle" {{ if .URL }} href="{{ .URL | relLangURL }}" {{ end }}>
You could reset the pointer, that's what I was getting at

2021-03-22 15:26 UTC, jkokkeler commented on assets/scss/templates/_navigation.scss
> +        display: block;
https://user-images.githubusercontent.com/1210221/112014463-342ab200-8b2b-11eb-81cb-b92107d6ce92.mp4

Please see attached, menu closes when selecting different menu items

2021-03-23 13:11 UTC, fabiopaiva commented on assets/scss/templates/_navigation.scss
> +        display: block;
fixed

2021-03-23 15:23 UTC, fabiopaiva commented on config.toml
> -URL = "solutions"
He suggested without the top

2021-03-24 15:12 UTC, jkokkeler approved these changes

2021-03-24 15:13 UTC, merged