Chore: add video work with us
DataWorkz-NL/dataworkz-site pull request #35
Opened 2021-03-17 10:43 UTC by fabiopaiva

closes #32

2021-03-19 08:43 UTC, jkokkeler requested changes
Please leave the other changes out of this review

2021-03-19 08:50 UTC, fabiopaiva commented
> Please leave the other changes out of this review

Rebased

2021-03-22 15:26 UTC, jkokkeler commented on assets/scss/templates/_homepage.scss
> +      left: 47%;
Please don't do this, leave the marker in the middle, and if needed you can use a negative padding if needed

2021-03-22 15:27 UTC, jkokkeler commented on layouts/partials/success-story-single.html
> +  <section class="section bg-cover" data-background="{{ .bg_image | absURL }}">
Please don't change this, the partials are being used on different pages, this will change the layout on different pages

2021-03-22 15:29 UTC, jkokkeler commented on layouts/career/list.html
> +        {{ partial "career-featured-video.html" . }}
Please look in the source code what this is actually doing, it breaks the flow of the semantic code, so you have a section in a section, not recommended. Either put it in a row or change the partial.

2021-03-23 10:09 UTC, fabiopaiva commented on layouts/career/list.html
> +        {{ partial "career-featured-video.html" . }}
sorry, but what is the problem with a nested section?

2021-03-23 10:11 UTC, fabiopaiva commented on layouts/partials/success-story-single.html
> +  <section class="section bg-cover" data-background="{{ .bg_image | absURL }}">
yes, it's a partial file. It will be changed everywhere it's used. Anything wrong with the changes?

2021-03-23 13:20 UTC, fabiopaiva commented on layouts/career/list.html
> +        {{ partial "career-featured-video.html" . }}
https://www.w3docs.com/learn-html/html-section-tag.html#example-of-the-html-span-class-tag-lt-section-gt-span-tag-inside-another-span-class-tag-lt-section-gt-span-tag-9

2021-03-23 13:55 UTC, jkokkeler commented on layouts/partials/success-story-single.html
> +  <section class="section bg-cover" data-background="{{ .bg_image | absURL }}">
Yes, your are changing the current order by removing the div.

2021-03-23 14:25 UTC, fabiopaiva commented on layouts/partials/success-story-single.html
> +  <section class="section bg-cover" data-background="{{ .bg_image | absURL }}">
fixed

2021-03-23 14:25 UTC, fabiopaiva commented on layouts/career/list.html
> +        {{ partial "career-featured-video.html" . }}
ok

2021-03-24 15:10 UTC, jkokkeler approved these changes

2021-03-24 15:12 UTC, merged